# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(default='', max_length=256)),
                ('content', models.TextField(default='')),
                ('audio_url', models.URLField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
